[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit LSM6DS@^4.7.4
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    WiFi